#!/bin/bash
echo "Starting E-Commerce Project..."
echo "This script requires tmux or multiple terminals"
echo ""
echo "Backend will run on http://localhost:3001"
echo "Frontend will run on http://localhost:3000"
echo "Database admin: http://localhost:8080"
echo ""
echo "Option 1: Using Docker Compose (Recommended)"
echo "  docker-compose up"
echo ""
echo "Option 2: Manual startup (requires 2 terminals)"
echo "  Terminal 1: bash start-backend.sh"
echo "  Terminal 2: bash start-frontend.sh"
